CREATE TABLE IF NOT EXISTS log_eventos (
    id SERIAL PRIMARY KEY,
    login VARCHAR(100) NOT NULL,
    nome_evento VARCHAR(100) NOT NULL,
    data_ocorrencia TIMESTAMP WITH TIME ZONE NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);